<!-- DO NOT EDIT THIS FILE. AUTO-GENERATED BY mobiletto-orm-typedef-gen -->

<template>
    <v-container>
        <v-row v-if="successSnackbar && successSnackbar.length > 0">
            <KitSnackbarSuccess :text="successSnackbar" />
        </v-row>
        <v-row v-else-if="errorSnackbar && errorSnackbar.length > 0">
            <KitSnackbarError :text="errorSnackbar" />
        </v-row>
        <v-row>
            <v-col>
                <h2>{{ adminTitle() }}</h2>
                <b v-if="messageExists('title_TestType_ee8faf4ceb_admin_details', messages)">
                    {{ messages.title_TestType_ee8faf4ceb_admin_details }}
                </b>
            </v-col>
        </v-row>
        <div>
            <v-row v-if="addingObject">
                <v-col>
                    <OrmForm
                        v-if="allRefsLoaded() && TestType_ee8faf4cebTypeDef"
                        form-name="add_TestType_ee8faf4ceb_form"
                        :type-def="TestType_ee8faf4cebTypeDef"
                        :type-name-message="typeNameMessage"
                        :thing="addObject"
                        :fields="TestType_ee8faf4cebTypeDefFields"
                        :create="true"
                        :read-only-object="() => false"
                        :server-errors="createTestType_ee8faf4cebServerErrors"
                        :label-prefixes="labelPfx"
                        :hint-suffixes="['_description']"
                        @submitted="onAddSubmitted"
                        @update="onAddUpdated"
                        @cancel="onAddCancel"
                    />
                </v-col>
            </v-row>
            <v-row v-else-if="Object.keys(editingObject).length > 0">
                <v-col>
                    <OrmForm
                        v-if="allRefsLoaded() && TestType_ee8faf4cebTypeDef"
                        form-name="edit_TestType_ee8faf4ceb_form"
                        :type-def="TestType_ee8faf4cebTypeDef"
                        type-name-message="typeNameMessage"
                        :thing="editingObject"
                        :fields="TestType_ee8faf4cebTypeDefFields"
                        :create="false"
                        :read-only-object="() => false"
                        :server-errors="editTestType_ee8faf4cebServerErrors"
                        :label-prefixes="labelPfx"
                        :hint-suffixes="['_description']"
                        @submitted="onEditSubmitted"
                        @update="onEditUpdated"
                        @cancel="onEditCancel"
                    />
                </v-col>
            </v-row>
            <v-row v-else-if="allRefsLoaded() && TestType_ee8faf4cebTypeDef">
                <v-col>
                    <v-container>
                        <v-row v-if="(TestType_ee8faf4cebList && TestType_ee8faf4cebList.length > 0) || searched">
                            <v-col>
                                <div>
                                    <v-form @submit.prevent="searchObjects">
                                        <div class="form-group">
                                            <v-text-field
                                                v-model="searchTerms"
                                                :label="messages.label_search"
                                                :disabled="TestType_ee8faf4cebStore.TestType_ee8faf4cebBusy"
                                                type="text"
                                                name="searchTerms"
                                                class="form-control"
                                                @keyup.enter="searchObjects"
                                            />
                                            <v-btn
                                                class="btn btn-primary"
                                                :disabled="TestType_ee8faf4cebStore.TestType_ee8faf4cebBusy"
                                                @click.stop="searchObjects"
                                            >
                                                <Icon name="material-symbols:search" />
                                            </v-btn>
                                        </div>
                                    </v-form>
                                </div>
                            </v-col>
                        </v-row>
                        <v-row>
                            <v-col>
                                <table v-if="TestType_ee8faf4cebList && TestType_ee8faf4cebList.length > 0">
                                    <thead>
                                        <tr>
                                            <th
                                                v-for="(tableField, tableFieldIndex) in tableFields"
                                                :key="tableFieldIndex"
                                            >
                                                {{ tableFieldMessages[tableField] }}
                                            </th>
                                            <th v-if="Object.keys(actionConfigs).length > 0">
                                                <Icon name="material-symbols:target" />
                                            </th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr v-for="(obj, objIndex) in TestType_ee8faf4cebList" :key="objIndex">
                                            <td v-for="(fieldName, fieldIndex) in tableFields" :key="fieldIndex">
                                                <OrmFieldDisplay
                                                    v-if="
                                                        TestType_ee8faf4cebTypeDef.fields[fieldName] ||
                                                        fieldName.startsWith('_meta')
                                                    "
                                                    :field="
                                                        fieldName.startsWith('_meta')
                                                            ? metaField(fieldName)
                                                            : TestType_ee8faf4cebTypeDef.fields[fieldName]
                                                    "
                                                    :value="deepGet(obj, fieldName)"
                                                />
                                            </td>
                                            <td v-if="Object.keys(actionConfigs).length > 0">
                                                <div
                                                    v-for="(action, actionIndex) in Object.keys(actionConfigs)"
                                                    :key="actionIndex"
                                                >
                                                    <NuxtLink
                                                        v-if="actionEnabled(obj, action)"
                                                        :to="{
                                                            path: `${actionConfig(action).path}/${deepGet(
                                                                obj,
                                                                TestType_ee8faf4cebTypeDef.idField(obj) as string,
                                                            )}`,
                                                        }"
                                                    >
                                                        <v-btn>
                                                            {{ messages[actionConfig(action).message] }}
                                                        </v-btn>
                                                    </NuxtLink>
                                                </div>
                                            </td>
                                            <td>
                                                <v-btn
                                                    v-if="canEdit(obj, TestType_ee8faf4cebList)"
                                                    :disabled="TestType_ee8faf4cebStore.TestType_ee8faf4cebBusy"
                                                    @click.stop="showEditOrm(obj)"
                                                >
                                                    <Icon name="material-symbols:edit" />
                                                </v-btn>
                                            </td>
                                            <td>
                                                <v-btn
                                                    v-if="canDelete(obj, TestType_ee8faf4cebList)"
                                                    :disabled="TestType_ee8faf4cebStore.TestType_ee8faf4cebBusy"
                                                    @click.stop="delObject(obj)"
                                                >
                                                    <Icon name="material-symbols:delete" />
                                                </v-btn>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </v-col>
                        </v-row>
                        <v-row>
                            <v-col>
                                <v-btn
                                    class="btn btn-primary"
                                    :disabled="TestType_ee8faf4cebStore.TestType_ee8faf4cebBusy"
                                    @click.stop="showAddOrm"
                                >
                                    <Icon name="material-symbols:add" />
                                </v-btn>
                            </v-col>
                        </v-row>
                    </v-container>
                </v-col>
            </v-row>
            <v-row v-else>
                <v-col>
                    <Icon name="material-symbols:clock-outline" />
                </v-col>
            </v-row>
        </div>
    </v-container>
</template>

<script setup lang="ts">
import { ref, watch, Ref } from "vue";
import { storeToRefs } from "pinia";
import {
    MobilettoOrmFieldDefConfig,
    MobilettoOrmObject,
    MobilettoOrmTypeDef,
    MobilettoOrmValidationErrors,
    metaField,
} from "mobiletto-orm-typedef";
import { TestType_ee8faf4cebType, TestType_ee8faf4cebTypeDef } from "mobiletto-orm-typedef-gen";
import { findMessage, messageExists, parseMessage, normalizeMsg } from "hokey-runtime";
import { useSessionStore } from "~/stores/sessionStore";
import { useTestType_ee8faf4cebStore } from "~/stores/model/TestType_ee8faf4cebStore";
import { deepUpdate } from "~/utils/model/adminHelper";
const successSnackbar = ref("");
const errorSnackbar = ref("");
type ActionConfig = {
    path: string;
    message: string;
    when: (obj: MobilettoOrmObject) => boolean;
};
const props = withDefaults(
    defineProps<{
        labelPrefixes: string[];
        typeNameMessage: string;
        actionConfigs: Record<string, ActionConfig>;
        msgAddSuccess: string;
        msgAddError: string;
        msgEditSuccess: string;
        msgEditError: string;
        msgDeleteSuccess: string;
        msgDeleteError: string;
        msgFindSingletonError: string;
        canEdit: (obj: MobilettoOrmObject, objList: MobilettoOrmObject[]) => boolean;
        canDelete: (obj: MobilettoOrmObject, objList: MobilettoOrmObject[]) => boolean;
        deleteConfirmationMessage: string;
    }>(),
    {
        labelPrefixes: () => ["label_", ""],
        typeNameMessage: () => "typename_TestType_ee8faf4ceb",
        actionConfigs: () => ({}),
        msgAddSuccess: () => "admin_info_added",
        msgAddError: () => "admin_info_add_error",
        msgEditSuccess: () => "admin_info_edited",
        msgEditError: () => "admin_info_edit_error",
        msgDeleteSuccess: () => "admin_info_deleted",
        msgDeleteError: () => "admin_info_delete_error",
        msgFindSingletonError: () => "admin_info_findSingleton_error",
        canEdit: () => true,
        canDelete: () => true,
    },
);

const emit = defineEmits<{
    added: [obj: TestType_ee8faf4cebType];
    addCanceled: [];
    edited: [obj: TestType_ee8faf4cebType];
    editCanceled: [obj: TestType_ee8faf4cebType];
    deleted: [obj: TestType_ee8faf4cebType];
}>();

const labelPfx: Ref<string[]> = ref(["admin_label_TestType_ee8faf4ceb_", "label_", ""]);
if (props.labelPrefixes) {
    props.labelPrefixes.forEach((p: string) => {
        if (!labelPfx.value.includes(p)) labelPfx.value.unshift(p);
    });
}

const sessionStore = useSessionStore();
const { localeMessages } = storeToRefs(sessionStore);
const messages = localeMessages;

const adminTitle = () =>
    messageExists("admin_title_TestType_ee8faf4ceb_administration", messages.value)
        ? messages.value.admin_title_TestType_ee8faf4ceb_administration
        : parseMessage("admin_title_site_administration", messages.value, {
              title: findMessage(props.typeNameMessage, messages.value, [""]),
          });

const addingObject = ref(false);
const addObject = ref({} as TestType_ee8faf4cebType);
const createTestType_ee8faf4cebServerErrors = ref({} as MobilettoOrmValidationErrors);

const editingObject = ref({} as TestType_ee8faf4cebType);
const editTestType_ee8faf4cebServerErrors = ref({} as MobilettoOrmValidationErrors);
const deleteTestType_ee8faf4cebServerErrors = ref({} as MobilettoOrmValidationErrors);

const pageNumber = ref(1);
const pageSize = ref(20);
const searchTerms = ref("");
const searched = ref(false);
const lastQuery = ref({});

const tableFields: Ref<string[]> = ref([]);

const tableFieldMessages: Ref<Record<string, string>> = ref({});
const initTableFieldMessages = (tableFields: string[]) => {
    const defaultTableFieldMessages: Record<string, string> = {};
    tableFields.forEach((f: string) => {
        defaultTableFieldMessages[f] = findMessage(normalizeMsg(f), messages.value, props.labelPrefixes);
    });
    tableFieldMessages.value = defaultTableFieldMessages;
};

const TestType_ee8faf4cebStore = useTestType_ee8faf4cebStore();
const { TestType_ee8faf4cebList } = storeToRefs(TestType_ee8faf4cebStore);
const TestType_ee8faf4cebTypeDef: Ref<MobilettoOrmTypeDef | null> = ref(null);
const TestType_ee8faf4cebTypeDefFields: Ref<MobilettoOrmFieldDefConfig[] | undefined> = ref(undefined);
const searchQuery = () => ({ textSearch: searchTerms.value });

const searchObjects = () => {
    const query = searchQuery();
    if (lastQuery.value && JSON.stringify(lastQuery.value) === JSON.stringify(query)) {
        // not sending duplicate search
    } else {
        searched.value = true;
        lastQuery.value = Object.assign({}, query);
        TestType_ee8faf4cebStore.search(query);
    }
};

const navigating = ref(false);

const allRefsLoaded = () => true;
TestType_ee8faf4cebTypeDef.value = TestType_ee8faf4cebTypeDef;
TestType_ee8faf4cebTypeDefFields.value = TestType_ee8faf4cebTypeDef.tabIndexedFields();
tableFields.value =
    TestType_ee8faf4cebTypeDef.value.tableFields && Array.isArray(TestType_ee8faf4cebTypeDef.value.tableFields)
        ? TestType_ee8faf4cebTypeDef.value.tableFields
        : TestType_ee8faf4cebTypeDef.value.primary
        ? [TestType_ee8faf4cebTypeDef.value.primary, "ctime", "mtime"]
        : ["id", "ctime", "mtime"];
initTableFieldMessages(tableFields.value);

const onAddUpdated = (update: { field: string; value: any }) => {
    deepUpdate(addObject.value, update.field, update.value);
};
const onAddSubmitted = async (obj: MobilettoOrmObject) => {
    await TestType_ee8faf4cebStore.create(obj as TestType_ee8faf4cebType, createTestType_ee8faf4cebServerErrors);
    addingObject.value = false;
    return await TestType_ee8faf4cebStore.search();
};
watch(createTestType_ee8faf4cebServerErrors, () => {
    if (Object.keys(createTestType_ee8faf4cebServerErrors).length > 0) {
        errorSnackbar.value = parseMessage(props.msgAddError, messages.value, {
            type: messages.value["typename_TestType_ee8faf4ceb"],
            id: TestType_ee8faf4cebTypeDef.id(obj),
            error: JSON.stringify(createTestType_ee8faf4cebServerErrors),
        });
    }
});
const showAddOrm = () => {
    addingObject.value = true;
};
const onAddCancel = () => {
    addingObject.value = false;
    emit("addCanceled");
};

const onEditUpdated = (update: { field: string; value: any }) => {
    if (editingObject.value) {
        deepUpdate(editingObject.value, update.field, update.value);
    }
};

const onEditSubmitted = async (obj: MobilettoOrmObject) => {
    await TestType_ee8faf4cebStore.update(obj as TestType_ee8faf4cebType, editTestType_ee8faf4cebServerErrors);
    editingObject.value = {} as TestType_ee8faf4cebType;
    return await TestType_ee8faf4cebStore.search();
};
watch(editTestType_ee8faf4cebServerErrors, () => {
    if (Object.keys(editTestType_ee8faf4cebServerErrors).length > 0) {
        errorSnackbar.value = parseMessage(props.msgDeleteError, messages.value, {
            type: messages.value["typename_TestType_ee8faf4ceb"],
            id: TestType_ee8faf4cebTypeDef.id(obj),
            error: JSON.stringify(editTestType_ee8faf4cebServerErrors),
        });
    }
});

const showEditOrm = (obj: MobilettoOrmObject) => {
    if (Object.keys(editingObject.value).length > 0) {
        // already editing something else
        return;
    }
    if (obj) {
        const id = TestType_ee8faf4cebTypeDef.id(obj);
        if (id && id.length > 0) {
            editingObject.value = JSON.parse(JSON.stringify(obj)) as TestType_ee8faf4cebType;
        }
    }
};
const onEditCancel = () => {
    emit("editCanceled", editingObject.value);
    editingObject.value = {} as TestType_ee8faf4cebType;
};

const actionConfig = (action: string) => {
    return props.actionConfigs[action];
};

const actionEnabled = (obj: MobilettoOrmObject, action: string) => {
    const cfg = props.actionConfigs[action];
    if (!cfg.when || typeof cfg.when !== "function") {
        return true;
    }
    if (typeof cfg.when === "function") {
        return cfg.when(obj) === true;
    }
    return true;
};
const delObject = (obj: MobilettoOrmObject) => {
    const id = TestType_ee8faf4cebTypeDef.id(obj);
    TestType_ee8faf4cebStore.delete(id, deleteTestType_ee8faf4cebServerErrors).then(() => {
        successSnackbar.value = parseMessage(props.msgDeleteSuccess, messages.value, {
            type: messages.value["typename_TestType_ee8faf4ceb"],
            id: TestType_ee8faf4cebTypeDef.id(obj),
        });
        return TestType_ee8faf4cebStore.search();
    });
};
watch(deleteTestType_ee8faf4cebServerErrors, () => {
    if (Object.keys(deleteTestType_ee8faf4cebServerErrors).length > 0) {
        errorSnackbar.value = parseMessage(props.msgDeleteError, messages.value, {
            type: messages.value["typename_TestType_ee8faf4ceb"],
            id: TestType_ee8faf4cebTypeDef.id(obj),
            error: JSON.stringify(deleteTestType_ee8faf4cebServerErrors),
        });
    }
});
watch(TestType_ee8faf4cebList, (newList) => {
    if (
        newList &&
        Array.isArray(newList) &&
        newList.length === 0 &&
        searchTerms.value &&
        searchTerms.value.length === 0
    ) {
        if (navigating.value) return;
        navigating.value = true;
        navigateTo("/admin/TestType_ee8faf4ceb/setup");
    }
});

const initRefs = async () => {};
TestType_ee8faf4cebStore.search();
</script>
